# Generated by Django 4.1.3 on 2022-11-17 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="profile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "profile_img",
                    models.ImageField(
                        default="default/profile.jpg", upload_to="profile_img"
                    ),
                ),
                ("bio", models.TextField(blank=True, max_length=500)),
            ],
        ),
    ]
